# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_preprocessing.ipynb.

# %% auto 0
__all__ = ['good_luck']

# %% ../nbs/00_preprocessing.ipynb 2
import numpy as np

# %% ../nbs/00_preprocessing.ipynb 3
def good_luck():
    return 'pass'
